In [20]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [64]:
import pandas as pd
import category_encoders as ce
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from src.utils import model_utils
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression


In [65]:
X_train = pd.read_csv('../data/input/X_train.csv')
y_train = pd.read_csv('../data/input/y_train.csv')

In [66]:
target_encoder = ce.TargetEncoder()
X = target_encoder.fit_transform(X_train, y_train)
X.head()

index    C1  banner_pos   site_id  site_domain  site_category    app_id  \
0  18201910  1005           0  0.118590     0.122438       0.128065  0.188735   
1  35141968  1005           1  0.298257     0.260324       0.180248  0.198970   
2  11358550  1005           0  0.118590     0.122438       0.128065  0.010814   
3  36241996  1005           0  0.118590     0.122438       0.128065  0.147823   
4   2987382  1005           0  0.205980     0.205980       0.208215  0.198970   

   app_domain  app_category  device_id  ...    C14  C15  C16   C17  C18  C19  \
0    0.182843      0.093020   0.147823  ...  16615  320   50  1863    3   39   
1    0.195158      0.199443   0.174547  ...  17264  320   50  1872    3   39   
2    0.023289      0.093020   0.174547  ...  21191  320   50  2424    1  161   
3    0.111282      0.107986   0.174547  ...  20751  320   50  1895    0  681   
4    0.195158      0.199443   0.174547  ...  21724  320   50  2502    0   35   

   C21  dayofweek  day  hour  
0   23          5   25    12  
1   23          2   29    15  
2   71          3   23    10  
3  101          3   30     0  
4  221          1   21    15  

[5 rows x 24 columns]

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y_train, stratify=y_train, test_size= 0.3, random_state= 42)

In [68]:
outcome = pd.DataFrame()
dummy_clf = DummyClassifier(strategy= "most_frequent")
dummy_clf.fit(X_train, y_train)
temp = model_utils.store_results(name='DummyClassifier',
                                 X_train=X_train,
                                 y_train=y_train,
                                 X_test=X_test,
                                 y_test=y_test,
                                 model=dummy_clf,
                                 folds=5)

outcome = pd.concat([outcome,temp])
outcome

Training data confusion matrix: 
 [[1174557       0]
 [ 240456       0]]
Test data confusion matrix: 
 [[503382      0]
 [103053      0]]


/home/stefan/PycharmProjects/exploration-ctr/src/utils/model_utils.py:21: RuntimeWarning: invalid value encountered in scalar divide
  recall = TP / (TP + FP)


model-name  accuracy-train  precision-train  recall-train  \
0  DummyClassifier        0.830068              0.0           NaN   

   accuracy_test  precision-test  recall-test  cross-val-mean  cross-val-1  \
0       0.830068             0.0          NaN        0.830068     0.830069   

   cross-val-2  cross-val-3  cross-val-4  cross-val-5  
0     0.830069     0.830065     0.830068     0.830068

In [69]:
scaler = MinMaxScaler()
X_train[X_train.columns] = scaler.fit_transform(X_train[X_train.columns])
X_train.head()

index        C1  banner_pos   site_id  site_domain  site_category  \
281816   0.700998  0.363636         0.0  0.242860     0.287645       0.404588   
1466266  0.272648  0.363636         0.0  0.139823     0.170980       0.248846   
956504   0.884906  0.363636         0.0  0.034133     0.028752       0.404588   
606180   0.704483  0.363636         0.0  0.139823     0.170980       0.248846   
1105485  0.086895  0.363636         0.0  0.242860     0.287645       0.404588   

           app_id  app_domain  app_category  device_id  ...       C14  \
281816   0.206170     0.30328      0.587333   0.219592  ...  0.907547   
1466266  0.195564     0.28352      0.247509   0.174786  ...  0.027960   
956504   0.206170     0.30328      0.587333   0.219592  ...  0.831862   
606180   0.074972     0.10605      0.295297   0.219592  ...  0.961651   
1105485  0.206170     0.30328      0.587333   0.219592  ...  0.901719   

              C15      C16       C17  C18       C19       C21  dayofweek  \
281816   0.221239  0.02988  0.911565  0.0  0.001107  0.866142   0.166667   
1466266  0.221239  0.02988  0.024943  1.0  0.716501  0.055118   0.500000   
956504   0.221239  0.02988  0.823507  1.0  0.001107  0.165354   0.333333   
606180   0.221239  0.02988  0.964853  0.0  0.000554  0.866142   0.166667   
1105485  0.221239  0.02988  0.903250  0.0  0.001107  0.866142   0.166667   

              day      hour  
281816   0.777778  0.347826  
1466266  0.222222  0.391304  
956504   0.888889  0.826087  
606180   0.777778  0.347826  
1105485  0.000000  0.782609  

[5 rows x 24 columns]

In [ ]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, np.ravel(y_train))

In [71]:
X_test[X_test.columns] = scaler.transform(X_test[X_test.columns])
X_test.head(2)

index        C1  banner_pos   site_id  site_domain  site_category  \
1620562  0.778320  0.363636    0.000000  0.593128     0.702505       0.404588   
453130   0.068612  0.363636    0.142857  0.283452     0.335722       0.350244   

          app_id  app_domain  app_category  device_id  ...       C14  \
1620562  0.20617     0.30328      0.587333   0.219592  ...  0.974068   
453130   0.20617     0.30328      0.587333   0.219592  ...  0.842041   

              C15      C16       C17       C18       C19       C21  dayofweek  \
1620562  0.221239  0.02988  0.972033  0.666667  0.716501  0.200787   0.166667   
453130   0.221239  0.02988  0.630385  0.000000  0.929125  0.185039   0.166667   

              day      hour  
1620562  0.777778  0.782609  
453130   0.000000  0.565217  

[2 rows x 24 columns]

In [72]:
y_pred = model.predict(X_test)
temp = model_utils.store_results(name='LogisticRegression',
                                 X_train=X_train,
                                 y_train=np.ravel(y_train),
                                 X_test=X_test,
                                 y_test=y_test,
                                 model=model,
                                 folds=5)
outcome = pd.concat([outcome,temp])
outcome

Training data confusion matrix: 
 [[1133758   40799]
 [  96231  144225]]
Test data confusion matrix: 
 [[485991  17391]
 [ 41103  61950]]


model-name  accuracy-train  precision-train  recall-train  \
0     DummyClassifier        0.830068         0.000000           NaN   
0  LogisticRegression        0.903160         0.599798      0.779493   

   accuracy_test  precision-test  recall-test  cross-val-mean  cross-val-1  \
0       0.830068        0.000000          NaN        0.830068     0.830069   
0       0.903544        0.601147     0.780807        0.903161     0.903012   

   cross-val-2  cross-val-3  cross-val-4  cross-val-5  
0     0.830069     0.830065     0.830068     0.830068  
0     0.902962     0.903160     0.903495     0.903174